apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: pavaan/py-hello:0.1
        name: hello
        ports:
        - containerPort: 5000
          name: health-check
        env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                key: URL
                name: world-config
            # value: "http://world-service"
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: PORT
                name: world-config
            # value: "5001"
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /
            port: health-check
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: health-check
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-service
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello
  type: NodePort