apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: world
  name: world
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - image: pavaan/py-world:0.1
        name: world
        ports:
        - containerPort: 5001
          name: health-check
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /
            port: health-check
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: health-check
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: world
  name: world-service
  namespace: default
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: world
  # type: NodePort